
import java.awt.Color;
import java.awt.Event;
import java.awt.event.KeyEvent;
import java.security.KeyPairGenerator;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author muhenestugtekin
 */
public class frmIntro extends javax.swing.JFrame {

    /**
     * Creates new form frmIntro
     */
    public frmIntro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jButton24 = new javax.swing.JButton();
        jButton25 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton26 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 153));

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(204, 255, 51));
        jButton2.setText("A");

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton3.setForeground(new java.awt.Color(204, 255, 51));
        jButton3.setText("B");

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton4.setForeground(new java.awt.Color(204, 255, 51));
        jButton4.setText("C");

        jButton5.setBackground(new java.awt.Color(255, 153, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton5.setForeground(new java.awt.Color(204, 255, 51));
        jButton5.setText("D");

        jButton6.setBackground(new java.awt.Color(255, 153, 153));
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton6.setForeground(new java.awt.Color(204, 255, 51));
        jButton6.setText("E");

        jButton7.setBackground(new java.awt.Color(255, 153, 153));
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(204, 255, 51));
        jButton7.setText("F");

        jButton8.setBackground(new java.awt.Color(255, 153, 153));
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton8.setForeground(new java.awt.Color(204, 255, 51));
        jButton8.setText("G");

        jButton9.setBackground(new java.awt.Color(255, 153, 153));
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton9.setForeground(new java.awt.Color(204, 255, 51));
        jButton9.setText("H");

        jButton10.setBackground(new java.awt.Color(255, 153, 153));
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton10.setForeground(new java.awt.Color(204, 255, 51));
        jButton10.setText("I");

        jButton11.setBackground(new java.awt.Color(255, 153, 153));
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton11.setForeground(new java.awt.Color(204, 255, 51));
        jButton11.setText("İ");

        jButton12.setBackground(new java.awt.Color(255, 153, 153));
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton12.setForeground(new java.awt.Color(204, 255, 51));
        jButton12.setText("J");

        jButton13.setBackground(new java.awt.Color(255, 153, 153));
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton13.setForeground(new java.awt.Color(204, 255, 51));
        jButton13.setText("K");

        jButton14.setBackground(new java.awt.Color(255, 153, 153));
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton14.setForeground(new java.awt.Color(204, 255, 51));
        jButton14.setText("L");

        jButton15.setBackground(new java.awt.Color(255, 153, 153));
        jButton15.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton15.setForeground(new java.awt.Color(204, 255, 51));
        jButton15.setText("M");

        jButton16.setBackground(new java.awt.Color(255, 153, 153));
        jButton16.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton16.setForeground(new java.awt.Color(204, 255, 51));
        jButton16.setText("N");

        jButton17.setBackground(new java.awt.Color(255, 153, 153));
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton17.setForeground(new java.awt.Color(204, 255, 51));
        jButton17.setText("O");
        jButton17.setMaximumSize(new java.awt.Dimension(45, 30));

        jButton18.setBackground(new java.awt.Color(255, 153, 153));
        jButton18.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton18.setForeground(new java.awt.Color(204, 255, 51));
        jButton18.setText("P");
        jButton18.setMaximumSize(new java.awt.Dimension(45, 30));

        jButton19.setBackground(new java.awt.Color(255, 153, 153));
        jButton19.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton19.setForeground(new java.awt.Color(204, 255, 51));
        jButton19.setText("R");
        jButton19.setMaximumSize(new java.awt.Dimension(47, 35));

        jButton20.setBackground(new java.awt.Color(255, 153, 153));
        jButton20.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton20.setForeground(new java.awt.Color(204, 255, 51));
        jButton20.setText("S");

        jButton21.setBackground(new java.awt.Color(255, 153, 153));
        jButton21.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton21.setForeground(new java.awt.Color(204, 255, 51));
        jButton21.setText("T");

        jButton22.setBackground(new java.awt.Color(255, 153, 153));
        jButton22.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton22.setForeground(new java.awt.Color(204, 255, 51));
        jButton22.setText("U");

        jButton23.setBackground(new java.awt.Color(255, 153, 153));
        jButton23.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton23.setForeground(new java.awt.Color(204, 255, 51));
        jButton23.setText("V");

        jButton24.setBackground(new java.awt.Color(255, 153, 153));
        jButton24.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton24.setForeground(new java.awt.Color(204, 255, 51));
        jButton24.setText("Y");

        jButton25.setBackground(new java.awt.Color(255, 153, 153));
        jButton25.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton25.setForeground(new java.awt.Color(204, 255, 51));
        jButton25.setText("Z");

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Soru:");

        jLabel2.setText("Cevap:");

        jTextField2.setBackground(new java.awt.Color(204, 204, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField2KeyPressed(evt);
            }
        });

        jButton26.setBackground(new java.awt.Color(255, 153, 255));
        jButton26.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton26.setText("Basla");
        jButton26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton26ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Dogru:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Yanlis:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("0");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("0");

        jLabel7.setBackground(new java.awt.Color(102, 255, 51));
        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText("yanitladiktan sonra enter tusuna basarak dogru-yanlis kontrolu yapabilirsiniz!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton24, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton25, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGap(616, 616, 616))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton5)
                            .addComponent(jButton23)
                            .addComponent(jButton3)
                            .addComponent(jButton2)
                            .addComponent(jButton25)
                            .addComponent(jButton24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton22)
                            .addComponent(jButton6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton21)
                            .addComponent(jButton7)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton20)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11)
                    .addComponent(jButton12)
                    .addComponent(jButton14)
                    .addComponent(jButton13)
                    .addComponent(jButton15)
                    .addComponent(jButton16))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton26, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int soruNo=0, dogru=0, yanlis=0;
    private void jButton26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton26ActionPerformed
        // TODO add your handling code here:
        jButton26.setText("Sonraki soru");
        soruNo++;
        jTextField2.setText("");
        if(soruNo == 1){
            jTextField1.setText("Ulkemizin guney kismindaki kiyi bolgesi?");
            jButton2.setBackground(Color.yellow);
        }
        if(soruNo == 2){
            jTextField1.setText("Yesilligiyle unlu marmara ilimiz?");
            jButton3.setBackground(Color.yellow);
        }
        if(soruNo == 3){
            jTextField1.setText("Muslumanlarin kutsal gunu?");
            jButton4.setBackground(Color.yellow);
        }
        if(soruNo == 4){
            jTextField1.setText("Karpuzuyla unlu ilimiz?");
            jButton5.setBackground(Color.yellow);
        }
        if(soruNo == 5){
            jTextField1.setText("Yeni kelimesinin zıt anlamlisi?");
            jButton6.setBackground(Color.yellow);
        }
        if(soruNo == 6){
            jTextField1.setText("Padisahin emirlerinin yazili hali?");
            jButton7.setBackground(Color.yellow);
        }
        if(soruNo == 7){
            jTextField1.setText("Dunyanin isi kaynagi?");
            jButton8.setBackground(Color.yellow);
        }
        if(soruNo == 8){
            jTextField1.setText("Ogrencilerin kotu karne getirince bakistigi nesne?");
            jButton9.setBackground(Color.yellow);
        }
        if(soruNo == 9){
            jTextField1.setText("Katik asi yemegiyle unlu ilimiz?");
            jButton10.setBackground(Color.yellow);
        }
        if(soruNo == 10){
            jTextField1.setText("Mersinin diger ismi?");
            jButton11.setBackground(Color.yellow);
        }
        if(soruNo == 11){
            jTextField1.setText("Askeri bir topluluk?");
            jButton12.setBackground(Color.yellow);
        }
        if(soruNo == 12){
            jTextField1.setText("Malatyanin meshur meyvesi?");
            jButton13.setBackground(Color.yellow);
        }
        if(soruNo == 13){
            jTextField1.setText("bir cicek ismi?");
            jButton14.setBackground(Color.yellow);
        }
        if(soruNo == 14){
            jTextField1.setText("Yilin ucuncu ayi?");
            jButton15.setBackground(Color.yellow);
        }
        if(soruNo == 15){
            jTextField1.setText("kokulu bir bitki, hastalanınca icilen?");
            jButton16.setBackground(Color.yellow);
        }
        if(soruNo == 16){
            jTextField1.setText("Halk sairi?");
            jButton17.setBackground(Color.yellow);
        }
        if(soruNo == 17){
            jTextField1.setText("Pirinc, havuc gibi sebzeler ile yapilan yemek?");
            jButton18.setBackground(Color.yellow);
        }
        if(soruNo == 18){
            jTextField1.setText("11 ayin sultani?");
            jButton19.setBackground(Color.yellow);
        }
        if(soruNo == 19){
            jTextField1.setText("Ingilizcede yilan?");
            jButton20.setBackground(Color.yellow);
        }
        if(soruNo == 20){
            jTextField1.setText("Turkiyenin megastari?");
            jButton21.setBackground(Color.yellow);
        }
        if(soruNo == 21){
            jTextField1.setText("Umit kelimesinin es anlamlisi?");
            jButton22.setBackground(Color.yellow);
        }
        if(soruNo == 22){
            jTextField1.setText("Kahvaltisi ile unlu ilimiz?");
            jButton23.setBackground(Color.yellow);
        }
        if(soruNo == 23){
            jTextField1.setText("Simsek kelimesinin es anlamlisi?");
            jButton24.setBackground(Color.yellow);
        }
        if(soruNo == 24){
            jTextField1.setText("Yagida yapilan bir besin?");
            jButton25.setBackground(Color.yellow);
        }
        
    }//GEN-LAST:event_jButton26ActionPerformed

    private void jTextField2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField2KeyPressed
        // TODO add your handling code here:
    if (evt.getKeyCode()==KeyEvent.VK_ENTER){
        switch (soruNo){
//            Cevap1
            case 1:
//                String cevap1 = "akdeniz";
                if(jTextField2.getText().equals("akdeniz")){
                    jButton2.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton2.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                
            //Cevap2
            case 2:
                if(jTextField2.getText().equals("bursa")){
                    jButton3.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton3.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
        
            //Cevap3
            case 3:
                if(jTextField2.getText().equals("cuma")){
                    jButton4.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton4.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                
            //Cevap4
            case 4:
                if(jTextField2.getText().equals("diyarbakir")){
                    jButton5.setBackground(Color.red);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton5.setBackground(Color.green);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;

                
            //Cevap5
            case 5:
                if(jTextField2.getText().equals("eski")){
                    jButton6.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton6.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                    
                }
                break;
                
            //Cevap6
            case 6:
                if(jTextField2.getText().equals("ferman")){
                    jButton7.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton7.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
            //Cevap7
            case 7:
                if(jTextField2.getText().equals("gunes")){
                    jButton8.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton8.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
            //Cevap8
            case 8:
                if(jTextField2.getText().equals("hali")){
                    jButton9.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton9.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
            //Cevap9
            case 9:
                if(jTextField2.getText().equals("igdir")){
                    jButton10.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton10.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap10
            case 10:
                if(jTextField2.getText().equals("icel")){
                    jButton11.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton11.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap11
            case 11:
                if(jTextField2.getText().equals("jandarma")){
                    jButton12.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton12.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap12
            case 12:
                if(jTextField2.getText().equals("kayisi")){
                    jButton13.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton13.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap13
            case 13:
                if(jTextField2.getText().equals("lale")){
                    jButton14.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton14.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap14
            case 14:
                if(jTextField2.getText().equals("mart")){
                    jButton15.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton15.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap15
            case 15:
                if(jTextField2.getText().equals("nane")){
                    jButton16.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton16.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap16
            case 16:
                if(jTextField2.getText().equals("ozan")){
                    jButton17.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton17.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap17
            case 17:
                if(jTextField2.getText().equals("pirasa")){
                    jButton18.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton18.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap18
            case 18:
                if(jTextField2.getText().equals("ramazan")){
                    jButton19.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton19.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap19
            case 19:
                if(jTextField2.getText().equals("snake")){
                    jButton20.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton20.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap20
            case 20:
                if(jTextField2.getText().equals("tarkan")){
                    jButton21.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton21.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap21
            case 21:
                if(jTextField2.getText().equals("umut")){
                    jButton22.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton22.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap22
            case 22:
                if(jTextField2.getText().equals("van")){
                    jButton23.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton23.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap23
            case 23:
                if(jTextField2.getText().equals("yildirim")){
                    jButton24.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton24.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
                //Cevap24
            case 24:
                if(jTextField2.getText().equals("zeytin")){
                    jButton25.setBackground(Color.green);
                    dogru++;
                    jLabel5.setText(String.valueOf(dogru));
                }
                else{
                    jButton25.setBackground(Color.red);
                    yanlis++;
                    jLabel6.setText(String.valueOf(yanlis));
                }
                break;
            
        }
    }//GEN-LAST:event_jTextField2KeyPressed

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmIntro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmIntro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton25;
    private javax.swing.JButton jButton26;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
